name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install coverage
          python -m pip install --upgrade pip pycodestyle
          pip install flask
          pip install flask_wtf
          pip install flask_sqlalchemy
          pip install flask_behind_proxy
          pip install pandas
          pip install wtforms
          pip install email_validator
          pip install wikipedia
          pip install praw
          pip install apiclient
      - name: Test with unittest
        run: |
          python3 -m unittest tests/testDaily.py
          python3 -m unittest tests/testLogin.py
          python3 -m unittest tests/testPage.py
          python3 -m unittest tests/testRegistration.py
      - name: Code coverage report
        run: |
          python3 -m coverage run -m unittest tests/testDaily.py
          python3 -m coverage run -m unittest tests/testLogin.py
          python3 -m coverage run -m unittest tests/testPage.py
          python3 -m coverage run -m unittest tests/testRegistration.py
          python3 -m coverage report
          python3 -m coverage html
      - name: Check Style
        run: |
          pycodestyle --first *.py